### ISSUE TITLE
camera blobs not presented

### ISSUE THREAD

**Issue by TechnoHT** [whatawurst/android_vendor_sony_poplar_kddi#6]
Firmware version: 47.2.C.1.126
`camera.poplar_kddi.so` were not presented, only `camera.msm8998.so` and `camera.qcom.so` in full system dump

**Comment by derfelot** [comment]
It's the `camera.qcom.so`. If you run the extract script, it will rename it to `camera.poplar_kddi.so`.

see: https://github.com/whatawurst/android_device_sony_poplar_kddi/blob/lineage-18.1/proprietary-files-vendor.txt#L402
